
// This file was automatically generated by the CoreABC TGI generator

  parameter APB_DWIDTH           = 32;
  parameter APB_SDEPTH           = 2;
  parameter APB_AWIDTH           = 14;
  parameter ICWIDTH              = 8;
  parameter ZRWIDTH              = 16;
  parameter IIWIDTH              = 1;
  parameter IFWIDTH              = 1;
  parameter IOWIDTH              = 1;
  parameter STWIDTH              = 4;
  parameter INITWIDTH            = 11;
  parameter INSMODE              = 0;
  parameter IMEM_APB_ACCESS      = 0;
  parameter ACT_CALIBRATIONDATA  = 1;
  parameter EN_RAM               = 0;
  parameter EN_ALURAM            = 0;
  parameter EN_INDIRECT          = 0;
  parameter EN_DATAM             = 2;
  parameter EN_INT               = 0;
  parameter ISRADDR              = 1;
  parameter EN_AND               = 1;
  parameter EN_XOR               = 0;
  parameter EN_OR                = 0;
  parameter EN_ADD               = 0;
  parameter EN_INC               = 0;
  parameter EN_SHL               = 0;
  parameter EN_SHR               = 0;
  parameter EN_CALL              = 0;
  parameter EN_PUSH              = 0;
  parameter EN_ACM               = 0;
  parameter EN_IOREAD            = 0;
  parameter EN_IOWRT             = 1;
  parameter EN_MULT              = 0;
  parameter HDL_license          = "U";
  parameter UNIQ_STRING_LENGTH   = 25;
  parameter UNIQ_STRING          = "DDR_MEMORY_CTRL_COREABC_0";
  parameter TESTMODE             = 0;
  parameter FAMILY               = 25;
  parameter ID                   = 0;
  parameter MAX_NVMDWIDTH        = 32;
  parameter TESTBENCH            = "User";
  parameter DEBUG                = 1;


